# Data: latency
# Config: security_authz_ip
# VM mode: nullvm
telemetry_mode: "none"
conn:
  - 2
  - 4
  - 8
  - 16

duration: 240
perf_record: false
run_bothsidecar: false
run_serversidecar: false
run_clientsidecar: false
run_baseline: false

jitter: false

run_ingress: "istio-ingressgateway.istio-system.svc.cluster.local/echo"
headers: "Host:fortioserver.fake-dns.org"
cacert: "/tmp/gateway-secret/tls.crt"

uniform: true
nocatchup: true
