# Data: cpu/mem
# Filter: metadata-exchange and stats filters
# VM mode: nullvm
telemetry_mode: "none"
conn:
  - 16
qps:
  - 10
  - 100
  - 200

duration: 240
perf_record: false
run_bothsidecar: false
run_serversidecar: false
run_clientsidecar: false
run_baseline: false

jitter: false

run_ingress: "https://istio-ingressgateway.istio-system.svc.cluster.local"
headers: "Host:fortioserver.fake-dns.org"
cacert: "/tmp/gateway-secret/tls.crt"

uniform: true
nocatchup: true
keepalive: true
connection_reuse: '1:60'
