telemetry_mode: "dryrun"
conn:
  - 8
qps:
  - 10
duration: 100
metrics:
  - p50
  - p90
  - p99
perf_record: false
run_bothsidecar: false
run_serversidecar: false
run_clientsidecar: false
run_baseline: false

run_ingress: "istio-ingressgateway.istio-system.svc.cluster.local/echo"
headers: "Host:fortioserver.fake-dns.org"
cacert: "/tmp/gateway-secret/tls.crt"

uniform: true
nocatchup: true